[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[]>=0.128.8",
    "grpcio>=1.78.0",
    "grpcio-reflection>=1.80.0",
    "grpcio-tools>=1.78.0",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.12.5",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.39.0",
]

[build-system]
requires = ["hatchling>=1.13"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]
